# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths: src/Application/**
  pull_request:
    branches: [ "main" ]
    paths: src/Application/**
env:
    registryName: stxnleot3pdwimpnpreg.azurecr.io
    repositoryName: techexcel/dotnetcoreapp
    dockerFolderPath: ./src/Application/src/RazorPagesTestSample
    tag: ${{ github.run_number }}

    
jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore src/Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj
    - name: Build
      run: dotnet build --no-restore src/Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal src/Application/tests/RazorPagesTestSample.Tests/RazorPagesTestSample.Tests.csproj
  push:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker login
      run: docker login $registryName -u ${{secrets.ACR_USERNAME}} -p ${{secrets.ACR_PASSWORD}}
    - name: Docker build
      run: docker build -t $registryName/$repositoryName:$tag --build-arg build_version=$tag $dockerFolderPath 
    - name: Docker push
      run: docker push $registryName/$repositoryName:$tag   
  deploy:
    runs-on: ubuntu-latest
    needs: push
    environment:
      name: dev
      url: https://stxnleot3pdwi-dev.azurewebsites.net/ 
    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v2.1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'stxnleot3pdwi-dev'
          images: stxnleot3pdwimpnpreg.azurecr.io/techexcel/dotnetcoreapp:${{github.run_number}}
